from __future__ import annotations

from datetime import date

from mci_gru.cockpit.models import (
    CockpitReport,
    Decision,
    GitHubAction,
    RunColor,
    Workstream,
    WorkstreamStatus,
)
from mci_gru.cockpit.render import render_cockpit_packet, render_workstream_register


def test_render_workstream_register_uses_controlled_columns() -> None:
    workstreams = [
        Workstream(
            name="LambdaRankIC",
            status=WorkstreamStatus.ACTIVE,
            tracker="GitHub issue #42",
            continuation="codex/lambdarankic-loss-optimization",
            source_of_truth="docs/research/README.md",
            latest_artifact="docs/handoffs/lambdarankic.md",
            last_verification="pytest tests/test_lambdarank_ic_loss.py -v",
            blocked_on="",
            next_action="Review benchmark evidence",
            owner="Codex",
            last_reviewed=date(2026, 6, 20),
        )
    ]

    markdown = render_workstream_register(workstreams, generated_on=date(2026, 6, 20))

    assert "# MCI-GRU Workstream Register" in markdown
    assert "| Workstream | Status | GitHub Issue / PR | Branch / Worktree |" in markdown
    assert (
        "| LambdaRankIC | active | GitHub issue #42 | "
        "codex/lambdarankic-loss-optimization |"
    ) in markdown
    assert "Generated by `scripts/refresh_cockpit.py` on 2026-06-20." in markdown


def test_render_cockpit_packet_surfaces_decision_queue_and_skipped_actions() -> None:
    report = CockpitReport(
        run_date=date(2026, 6, 20),
        color=RunColor.YELLOW,
        executive_summary="One local-only workstream needs a user decision.",
        decisions=[
            Decision(
                workstream="Portfolio-IC",
                question="Choose whether to promote the weight sweep evidence.",
                options="Promote, park, or request another validation run.",
            )
        ],
        active_workstreams=[
            Workstream(
                name="Portfolio-IC",
                status=WorkstreamStatus.NEEDS_USER_DECISION,
                tracker="",
                continuation="local handoff",
                source_of_truth="docs/handoffs/2026-05-31-portfolio-ic-weight-sweep.md",
                latest_artifact="portfolio_ic_full_weight_sweep_results.csv",
                last_verification="artifact review only",
                blocked_on="user decision",
                next_action="Pick promotion path",
                owner="User",
                last_reviewed=date(2026, 6, 20),
            )
        ],
        blocked_workstreams=[],
        local_only_work=[],
        stale_or_archive_candidates=[],
        github_actions_taken=[],
        github_actions_skipped=[
            GitHubAction(
                action="comment",
                target="MCI-GRU Cockpit issue",
                reason="GitHub sync disabled",
            )
        ],
        verification_notes=["Local artifact render only; no GitHub mutation."],
        evidence_gaps=["No live GitHub issue scan in local-only mode."],
    )

    markdown = render_cockpit_packet(report)

    assert "# MCI-GRU Cockpit - 2026-06-20" in markdown
    assert "**Run color:** yellow" in markdown
    assert "## Decision Queue" in markdown
    assert "Choose whether to promote the weight sweep evidence." in markdown
    assert "## GitHub Actions Proposed Or Skipped" in markdown
    assert "GitHub sync disabled" in markdown
