"""Helpers for the first admitted run's Colab notebook (#187, #278).

``notebooks/first_run_colab.ipynb`` (generated by ``scripts/gen_first_run_colab_nb.py``)
clones the repository, installs ``requirements.lock`` and then imports this module
from the checkout. Keeping the logic here rather than in notebook cells lets the
tests exercise it directly.

What it does:

- Reads the run's Hydra overrides and slug from ``docs/DEFAULT_EXPERIMENT_RECIPE.md``
  at the cloned commit, so the notebook runs whatever recipe that commit freezes
  instead of a copy that can drift from it.
- Says which open pull request a recipe still lacks before an admitted run
  (#270, #274, #275), so a run on a commit without them is refused by name.
- Stages, from Drive into ``data/raw``, the published package the recipe's data
  config declares, and verifies it. The Drive copy must prove it is that package
  (a historical ``MANIFEST.txt`` whose digest the manifest records, or a copy of
  the manifest itself), its inventory must equal the manifest's file records, and
  the staged package must pass ``validate_input_package``.
- Stages the EODHD S&P 500 index file the regime market input reads (#276).
- Copies the run folder to Drive while the run is going, without ever deleting.

Nothing here overwrites a file whose bytes differ from the pinned ones: staging
stops instead, and the conflicting file is left as it was.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from mci_gru.data.input_manifest import (
    PackageVerification,
    read_input_manifest,
    validate_input_package,
)

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

RECIPE_PATH = "docs/DEFAULT_EXPERIMENT_RECIPE.md"

#: The selected July 31 package, its committed r1 manifest and that manifest's digest
#: (the value #270 pins as ``data.input_package_manifest_sha256``).
PACKAGE_MANIFEST = "data/manifests/sp500_pit_gics_top10_mcap_monthly_20160104_20260731.r1.json"
PACKAGE_MANIFEST_SHA256 = "1e2043dcb4f00a88de128985cc94423c122e480034c16ec741710a2460653ecf"
PACKAGE_ROOT = "data/raw"
#: The 2026-10-02 Drive preservation copy, restored on its own on 2026-10-03 (#207).
PACKAGE_DRIVE_DIR = (
    "/content/drive/MyDrive/MCI_GRU_shared/preservation/2026-10-02-110-universe-2016"
)
HISTORICAL_INVENTORY_NAME = "MANIFEST.txt"


@dataclass(frozen=True)
class PublishedPackage:
    """A published input package and where its preserved copy lives on Drive."""

    manifest: str
    manifest_sha256: str
    drive_dir: str
    #: How the Drive copy shows it is this package: ``historical_inventory`` (a
    #: MANIFEST.txt whose digest the manifest records) or ``manifest_copy`` (the
    #: manifest's own bytes at the top of the folder).
    drive_inventory: str


#: The packages a data config may declare for the run, by manifest digest. The
#: notebook stages whichever one the recipe's data config names, so moving the
#: recipe to another package is a change to the recipe, not to the notebook.
LSEG_PACKAGE = PublishedPackage(
    PACKAGE_MANIFEST, PACKAGE_MANIFEST_SHA256, PACKAGE_DRIVE_DIR, "historical_inventory"
)
#: The same 110-name membership priced from EODHD (#281, #282), r2, published
#: 2026-10-09. Its Drive folder carries a byte copy of the manifest at its top.
#: The r1 package it replaced must never be staged, so it has no entry.
EODHD_PACKAGE = PublishedPackage(
    "data/manifests/sp500_pit_gics_top10_mcap_monthly_20160104_20260731_eodhd.r2.json",
    "dcebb8ef9f1f3105c2f925d76c468fba32c220642908bf1a96b6f123f569d1c0",
    "/content/drive/MyDrive/MCI_GRU_shared/preservation/"
    "eodhd_sp500_pit_gics_top10_mcap_monthly_20160104_20260731_r2",
    "manifest_copy",
)
PUBLISHED_PACKAGES = {package.manifest_sha256: package for package in (LSEG_PACKAGE, EODHD_PACKAGE)}

#: Same values as ``scripts/nb_lib.py``; ``tests/test_first_run_colab.py`` pins that.
EODHD_MARKET_RELATIVE = "data/raw/market/eodhd_sp500_2010_20260919/sp500_index.csv"
EODHD_MARKET_SHA256 = "9f5cfaf5e9f057065b83619b01568164e1f61a45df9453c66269fb54f080f5ac"
EODHD_MARKET_SIZE = 351815
#: Its own folder beside the package, so the package's ten-file inventory is untouched.
EODHD_MARKET_DRIVE_PATH = (
    "/content/drive/MyDrive/MCI_GRU_shared/preservation/eodhd_sp500_2010_20260919/sp500_index.csv"
)

#: Smoke runs keep every recipe semantic except the ensemble and epoch budget.
SMOKE_BUDGET = {"training.num_models": "1", "training.num_epochs": "2"}

_OVERRIDE_BLOCK = re.compile(r"^## Hydra Overrides\n+```text\n(.*?)^```", re.M | re.S)
_SLUG_BLOCK = re.compile(r"^Recipe slug:\n+```text\n(.*?)^```", re.M | re.S)


class StagingError(RuntimeError):
    """An input could not be staged with exactly the pinned bytes."""


@dataclass(frozen=True)
class Prerequisite:
    """One piece an admitted run needs from the cloned commit."""

    pull_request: str
    description: str
    present: bool


# ---------------------------------------------------------------------------
# Recipe
# ---------------------------------------------------------------------------


def recipe_overrides(text: str) -> list[str]:
    """The Hydra overrides in the recipe's override block, in order."""
    match = _OVERRIDE_BLOCK.search(text)
    if match is None:
        raise ValueError("The recipe has no '## Hydra Overrides' text block")
    overrides = [line.strip() for line in match.group(1).splitlines() if line.strip()]
    keys = [override.split("=", 1)[0] for override in overrides]
    duplicates = sorted({key for key in keys if keys.count(key) > 1})
    if duplicates:
        raise ValueError(f"The recipe sets these keys more than once: {duplicates}")
    return overrides


def recipe_slug(text: str) -> str:
    """The recipe slug, the one line in the block under 'Recipe slug:'."""
    match = _SLUG_BLOCK.search(text)
    if match is None:
        raise ValueError("The recipe has no 'Recipe slug:' text block")
    lines = [line.strip() for line in match.group(1).splitlines() if line.strip()]
    if len(lines) != 1:
        raise ValueError(f"The recipe slug block must hold one line, found {len(lines)}")
    return lines[0]


def override_value(overrides: Sequence[str], key: str) -> str | None:
    for override in overrides:
        name, _, value = override.partition("=")
        if name == key:
            return value
    return None


def replace_override(overrides: Sequence[str], key: str, value: str) -> list[str]:
    """Set ``key=value`` in place. Hydra refuses a key given twice, so never append."""
    found = False
    result = []
    for override in overrides:
        if override.partition("=")[0] == key:
            result.append(f"{key}={value}")
            found = True
        else:
            result.append(override)
    if not found:
        raise KeyError(f"The recipe does not set {key}")
    return result


#: The keys #270 added to a data config to declare its input package.
PACKAGE_DECLARATION_KEYS = (
    "input_package_manifest",
    "input_package_manifest_sha256",
    "input_package_root",
)
#: The prerequisite row for the notebook's own pin table (#285). Neither mode can run
#: without it, because no other package is ever staged in its place.
PACKAGE_PIN_PREREQUISITE = "#285"


def recipe_data_config(repo_dir: Path) -> dict[str, Any]:
    """The data config the recipe selects with ``data=``, or ``{}`` if there is none."""
    repo_dir = Path(repo_dir)
    overrides = recipe_overrides((repo_dir / RECIPE_PATH).read_text(encoding="utf-8"))
    data_group = override_value(overrides, "data")
    path = repo_dir / "configs" / "data" / f"{data_group}.yaml"
    if not data_group or not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def declared_package(data_config: dict[str, Any]) -> PublishedPackage | None:
    """The published package a data config declares, if it is one this notebook knows."""
    package = PUBLISHED_PACKAGES.get(data_config.get("input_package_manifest_sha256"))
    if (
        package is None
        or data_config.get("input_package_manifest") != package.manifest
        or data_config.get("input_package_root") != PACKAGE_ROOT
    ):
        return None
    return package


def selected_package(repo_dir: Path) -> PublishedPackage:
    """The package the recipe at this checkout runs on; stops if it is not a known one."""
    data_config = recipe_data_config(repo_dir)
    package = declared_package(data_config)
    if package is None:
        raise StagingError(
            "The recipe's data config does not declare a package this notebook knows: "
            f"manifest {data_config.get('input_package_manifest')!r}, sha256 "
            f"{data_config.get('input_package_manifest_sha256')!r}, root "
            f"{data_config.get('input_package_root')!r}"
        )
    return package


def admitted_run_prerequisites(repo_dir: Path) -> list[Prerequisite]:
    """What an admitted run needs from open pull requests, read from the checkout."""
    repo_dir = Path(repo_dir)
    overrides = recipe_overrides((repo_dir / RECIPE_PATH).read_text(encoding="utf-8"))
    data_config = recipe_data_config(repo_dir)
    declarations = repo_dir / "mci_gru" / "evaluation" / "run_input_declarations.py"
    declarations_text = declarations.read_text(encoding="utf-8") if declarations.exists() else ""
    return [
        Prerequisite(
            "#270",
            "each window attaches its declared package and observed reads "
            "(the data config declares a package manifest, its SHA-256 and the package root)",
            (repo_dir / "mci_gru" / "evaluation" / "run_input_attachments.py").exists()
            and all(data_config.get(key) for key in PACKAGE_DECLARATION_KEYS)
            and data_config.get("input_package_root") == PACKAGE_ROOT,
        ),
        Prerequisite(
            PACKAGE_PIN_PREREQUISITE,
            "this notebook holds a pin for the package the recipe's data config declares",
            declared_package(data_config) is not None,
        ),
        Prerequisite(
            "#274",
            "the recipe captures its regime inputs (data.auxiliary_snapshot_mode=capture)",
            override_value(overrides, "data.auxiliary_snapshot_mode") == "capture",
        ),
        Prerequisite(
            "#274",
            "the EODHD S&P 500 file is a declared input role (eodhd.sp500_index)",
            "MARKET_FILE_ROLE" in declarations_text,
        ),
        Prerequisite(
            "#275",
            "the recipe pins data-dependent latents, the residual cross-stock block "
            "and 32-then-10 gru_attn layers",
            override_value(overrides, "model.market_latent_mode") == "data_dependent"
            and override_value(overrides, "model.cross_section_block") == "residual"
            and override_value(overrides, "model.gru_attn_layer_widths") == "per_layer",
        ),
    ]


def build_run_overrides(
    recipe: Sequence[str],
    *,
    run_dir: Path,
    experiment_name: str,
    smoke: bool,
) -> list[str]:
    """The recipe's overrides plus where this run writes; budgets change only for smoke.

    Capture is added only when the recipe does not already select it (main before
    #274). The folder is named explicitly then, because before #274 capture has no
    default folder; from #274 on, the default is the same ``input_snapshots/``.
    MLflow tracking is switched off: ``requirements.lock`` does not carry the
    ``tracking`` extra, and the run's own records do not depend on it.
    """
    overrides = list(recipe)
    if smoke:
        for key, value in SMOKE_BUDGET.items():
            overrides = replace_override(overrides, key, value)
    if override_value(overrides, "data.auxiliary_snapshot_mode") is None:
        overrides += [
            "data.auxiliary_snapshot_mode=capture",
            f"data.auxiliary_snapshot_directory={Path(run_dir) / 'input_snapshots'}",
        ]
    if override_value(overrides, "tracking.enabled") is None:
        overrides.append("tracking.enabled=false")
    else:
        overrides = replace_override(overrides, "tracking.enabled", "false")
    overrides += [
        f"hydra.run.dir={run_dir}",
        f"experiment_name={experiment_name}",
    ]
    return overrides


# ---------------------------------------------------------------------------
# Staging
# ---------------------------------------------------------------------------


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _check(path: Path, sha256: str, size: int, what: str) -> None:
    observed_size = path.stat().st_size
    observed_sha256 = sha256_of(path)
    if observed_size != size or observed_sha256 != sha256:
        raise StagingError(
            f"{what} at {path} does not match its pin: expected {size} bytes, "
            f"sha256 {sha256}; found {observed_size} bytes, sha256 {observed_sha256}. "
            "Nothing was replaced."
        )


def stage_verified_file(source: Path, target: Path, *, sha256: str, size: int) -> str:
    """Copy ``source`` to ``target`` only if both hold exactly the pinned bytes.

    Returns ``"reused"`` when ``target`` already holds them and ``"copied"`` after a
    copy. A ``target`` with other bytes is never replaced, and a ``source`` with
    other bytes is never copied.
    """
    source, target = Path(source), Path(target)
    if target.exists():
        _check(target, sha256, size, "The file already in place")
        return "reused"
    if not source.exists():
        raise StagingError(f"Missing on Drive: {source}")
    _check(source, sha256, size, "The Drive copy")
    target.parent.mkdir(parents=True, exist_ok=True)
    partial = target.with_name(target.name + ".partial")
    if partial.exists():
        raise StagingError(f"A partial copy from an earlier attempt is in the way: {partial}")
    shutil.copyfile(source, partial)
    _check(partial, sha256, size, "The copy")
    os.replace(partial, target)
    return "copied"


def _git_bytes(repo_dir: Path, *args: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(repo_dir), *args], check=True, capture_output=True
    ).stdout


def align_tracked_line_endings(
    repo_dir: Path, inventory: dict[str, tuple[str, int]], *, package_root: str = PACKAGE_ROOT
) -> list[str]:
    """Give package files that git tracks their pinned bytes in a fresh clone.

    Two of the package's sidecars are tracked in git with LF line endings, while
    the package pins the Windows CRLF bytes they were preserved with. A Linux clone
    therefore holds other bytes at those paths. For each tracked path whose bytes
    differ from its pin, this checks that the committed blob with CRLF line endings
    has exactly the pinned digest and size, records ``text eol=crlf`` for that path
    in ``.git/info/attributes`` (local to this clone), and has git check the path
    out again, which writes those bytes. Git then reports the file unchanged. Any other difference stops. Returns the paths
    it realigned.
    """
    repo_dir = Path(repo_dir)
    aligned = []
    for relative, (sha256, size) in sorted(inventory.items()):
        repo_path = f"{package_root}/{relative}"
        listed = subprocess.run(
            ["git", "-C", str(repo_dir), "ls-files", "--error-unmatch", "--", repo_path],
            capture_output=True,
        )
        if listed.returncode != 0:
            continue
        target = repo_dir / repo_path
        if target.exists() and target.stat().st_size == size and sha256_of(target) == sha256:
            continue
        crlf = re.sub(rb"(?<!\r)\n", b"\r\n", _git_bytes(repo_dir, "show", f"HEAD:{repo_path}"))
        if len(crlf) != size or hashlib.sha256(crlf).hexdigest() != sha256:
            raise StagingError(
                f"{repo_path} is tracked in git with bytes that are not the package's, "
                "even with CRLF line endings. Nothing was changed."
            )
        attributes = repo_dir / ".git" / "info" / "attributes"
        rule = f"/{repo_path} text eol=crlf\n"
        existing = attributes.read_text(encoding="utf-8") if attributes.exists() else ""
        if rule not in existing.splitlines(keepends=True):
            attributes.parent.mkdir(parents=True, exist_ok=True)
            with open(attributes, "a", encoding="utf-8") as handle:
                handle.write(("" if not existing or existing.endswith("\n") else "\n") + rule)
        # Git writes the file itself, so its index records the new stat and the path
        # reads as unchanged; writing the bytes directly leaves a size the index
        # does not match, which git status reports as a change.
        target.unlink(missing_ok=True)
        _git_bytes(repo_dir, "checkout", "--", repo_path)
        if target.stat().st_size != size or sha256_of(target) != sha256:
            raise StagingError(f"{repo_path} did not check out with its pinned bytes.")
        status = _git_bytes(repo_dir, "status", "--porcelain", "--", repo_path)
        if status.strip():
            raise StagingError(f"{repo_path} still reads as changed to git: {status.decode()}")
        aligned.append(relative)
    return aligned


def parse_historical_inventory(raw: bytes) -> dict[str, tuple[str, int]]:
    """``{path: (sha256, size)}`` from a ``sha256  bytes  path`` MANIFEST.txt."""
    inventory: dict[str, tuple[str, int]] = {}
    for number, line in enumerate(raw.decode("utf-8").splitlines(), start=1):
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) != 3 or not re.fullmatch(r"[0-9a-f]{64}", fields[0]):
            raise StagingError(f"MANIFEST.txt line {number} is not 'sha256 bytes path'")
        sha256, size, path = fields
        if not size.isdigit():
            raise StagingError(f"MANIFEST.txt line {number} has a non-integer size")
        if path in inventory:
            raise StagingError(f"MANIFEST.txt lists {path} twice")
        inventory[path] = (sha256, int(size))
    if not inventory:
        raise StagingError("MANIFEST.txt lists no files")
    return inventory


@dataclass(frozen=True)
class StagedPackage:
    verification: PackageVerification
    outcomes: dict[str, str]
    drive_inventory_sha256: str

    def summary(self) -> dict[str, Any]:
        return {
            "package_id": self.verification.snapshot.manifest.package_id,
            "package_revision": self.verification.snapshot.manifest.package_revision,
            "manifest_sha256": self.verification.snapshot.sha256,
            "drive_inventory_sha256": self.drive_inventory_sha256,
            "files": [
                {
                    "path": observation.record.path,
                    "sha256": observation.sha256,
                    "size_bytes": observation.size_bytes,
                    "staging": self.outcomes[observation.record.path],
                }
                for observation in self.verification.files
            ],
        }


def stage_package(
    repo_dir: Path,
    drive_dir: Path,
    *,
    manifest: str = PACKAGE_MANIFEST,
    manifest_sha256: str = PACKAGE_MANIFEST_SHA256,
    drive_inventory: str = "historical_inventory",
) -> StagedPackage:
    """Stage a preserved package from Drive into ``data/raw`` and verify all of it.

    The Drive copy must carry the inventory the committed manifest vouches for:
    either a ``MANIFEST.txt`` with the digest the manifest records for its historical
    inventory, which must then equal the manifest's file records path for path, hash
    for hash and size for size; or a byte-identical copy of the manifest, whose own
    records are then the inventory. Every staged file must have its pinned bytes, and
    the staged package must pass ``validate_input_package``. Only the
    ``MANIFEST.txt`` route is an independent second inventory.
    """
    repo_dir, drive_dir = Path(repo_dir), Path(drive_dir)
    snapshot = read_input_manifest(repo_dir / manifest, expected_sha256=manifest_sha256)
    declared = {
        record.path: (record.sha256, record.size_bytes) for record in snapshot.manifest.files
    }
    if drive_inventory == "historical_inventory":
        recorded = snapshot.manifest.metadata.get("historical_inventory", {})
        inventory_path = drive_dir / HISTORICAL_INVENTORY_NAME
        expected = (recorded.get("sha256"), recorded.get("size_bytes"))
    elif drive_inventory == "manifest_copy":
        inventory_path = drive_dir / Path(manifest).name
        expected = (snapshot.sha256, len(snapshot.raw_bytes))
    else:
        raise ValueError(f"Unknown Drive inventory kind {drive_inventory!r}")
    if not inventory_path.exists():
        raise StagingError(f"Missing on Drive: {inventory_path}")
    inventory_bytes = inventory_path.read_bytes()
    inventory_sha256 = hashlib.sha256(inventory_bytes).hexdigest()
    if (inventory_sha256, len(inventory_bytes)) != expected:
        raise StagingError(
            f"{inventory_path} is not the inventory the manifest vouches for: expected "
            f"sha256 {expected[0]} ({expected[1]} bytes), found "
            f"{inventory_sha256} ({len(inventory_bytes)} bytes)"
        )
    inventory = (
        parse_historical_inventory(inventory_bytes)
        if drive_inventory == "historical_inventory"
        else dict(declared)
    )
    if inventory != declared:
        raise StagingError(
            "The Drive inventory and the manifest disagree: only on Drive "
            f"{sorted(set(inventory) - set(declared))}, only in the manifest "
            f"{sorted(set(declared) - set(inventory))}, different bytes "
            f"{sorted(p for p in set(inventory) & set(declared) if inventory[p] != declared[p])}"
        )
    package_root = repo_dir / PACKAGE_ROOT
    aligned = (
        align_tracked_line_endings(repo_dir, inventory) if (repo_dir / ".git").exists() else []
    )
    outcomes = {
        path: stage_verified_file(drive_dir / path, package_root / path, sha256=sha256, size=size)
        for path, (sha256, size) in sorted(inventory.items())
    }
    outcomes.update({path: "aligned" for path in aligned})
    verification = validate_input_package(snapshot, package_root, expected_paths=list(inventory))
    return StagedPackage(verification, outcomes, inventory_sha256)


def stage_eodhd_market_file(
    repo_dir: Path, drive_path: Path | str = EODHD_MARKET_DRIVE_PATH
) -> str:
    """Stage the EODHD S&P 500 index file at the path the recipe's feature group reads."""
    return stage_verified_file(
        Path(drive_path),
        Path(repo_dir) / EODHD_MARKET_RELATIVE,
        sha256=EODHD_MARKET_SHA256,
        size=EODHD_MARKET_SIZE,
    )


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------


def lock_pins(lock_text: str) -> dict[str, str]:
    """``{normalized name: version}`` for every ``name==version`` line of a pip-compile lock."""
    pins = {}
    for line in lock_text.splitlines():
        match = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)", line)
        if match:
            pins[re.sub(r"[-_.]+", "-", match.group(1)).lower()] = match.group(2)
    return pins


def lock_mismatches(pins: dict[str, str], installed: Callable[[str], str | None]) -> list[str]:
    """Pins the environment does not satisfy. A local suffix such as ``+cu130`` is allowed."""
    problems = []
    for name, version in sorted(pins.items()):
        found = installed(name)
        if found is None:
            problems.append(f"{name}: not installed (lock pins {version})")
        elif found.split("+", 1)[0] != version:
            problems.append(f"{name}: {found} installed, lock pins {version}")
    return problems


# ---------------------------------------------------------------------------
# Running and copying to Drive
# ---------------------------------------------------------------------------


def sync_to_drive(local_dir: Path, drive_dir: Path) -> int:
    """Copy new or changed files from ``local_dir`` to ``drive_dir``. Never deletes.

    The run itself writes to local disk: snapshot capture publishes with hard links,
    and Colab's Drive mount is not known to support them. Returns the number of files copied.
    """
    local_dir, drive_dir = Path(local_dir), Path(drive_dir)
    copied = 0
    for source in sorted(local_dir.rglob("*")):
        # Capture stages each manifest under a temporary name before publishing it.
        if not source.is_file() or source.name.startswith(".input-manifest-"):
            continue
        target = drive_dir / source.relative_to(local_dir)
        stat = source.stat()
        if target.exists():
            existing = target.stat()
            if existing.st_size == stat.st_size and existing.st_mtime >= stat.st_mtime:
                continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        copied += 1
    return copied


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def run_with_drive_sync(
    command: Sequence[str],
    *,
    cwd: Path,
    local_dir: Path,
    drive_dir: Path,
    every_seconds: float = 600.0,
    env: dict[str, str] | None = None,
    echo: Callable[[str], None] = print,
) -> int:
    """Run ``command``, echo its output, and copy ``local_dir`` to Drive as it goes.

    Copies run on a timer thread, so a slow copy never blocks the run's output
    pipe, and a failed copy (a dropped Drive mount, a full quota) is reported and
    retried at the next tick instead of stopping training. A heartbeat file on
    Drive records the last copy. The final copy runs whatever the exit code.
    """
    local_dir, drive_dir = Path(local_dir), Path(drive_dir)
    heartbeat = drive_dir / "colab_heartbeat.json"
    started = datetime.now(timezone.utc).isoformat()

    def copy_now(state: str, **extra: Any) -> None:
        try:
            copied = sync_to_drive(local_dir, drive_dir) if local_dir.exists() else 0
            write_json(
                heartbeat,
                {
                    "started_at_utc": started,
                    "last_copy_at_utc": datetime.now(timezone.utc).isoformat(),
                    "files_copied": copied,
                    "state": state,
                    **extra,
                },
            )
        except OSError as error:
            echo(f"[drive copy] failed, will retry: {error}")

    stop = threading.Event()

    def copy_periodically() -> None:
        while not stop.wait(every_seconds):
            copy_now("running")

    run_env = dict(os.environ if env is None else env)
    run_env["PYTHONUNBUFFERED"] = "1"
    process = subprocess.Popen(
        list(command),
        cwd=cwd,
        env=run_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert process.stdout is not None
    copier = threading.Thread(target=copy_periodically, daemon=True)
    copier.start()
    returncode = None
    try:
        for line in process.stdout:
            echo(line.rstrip("\n"))
        returncode = process.wait()
    finally:
        if returncode is None:
            process.kill()
            returncode = process.wait()
        stop.set()
        copier.join()
        copy_now("finished", returncode=returncode)
    return returncode


# ---------------------------------------------------------------------------
# Command line, so the notebook never imports repository code into its kernel
# ---------------------------------------------------------------------------

REPO_DIR = Path(__file__).resolve().parents[1]
EVIDENCE_LABELS = {
    "full": "first admitted run candidate (#187); admission still needs the owner's receipt",
    "smoke": "smoke, not evidence: 1 model x 2 epochs, mechanics only",
}


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO_DIR), *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def _installed_version(name: str) -> str | None:
    from importlib import metadata

    try:
        return metadata.version(name)
    except metadata.PackageNotFoundError:
        return None


def _command_check_env(args: Any) -> int:
    import platform
    import sys

    import torch

    problems = lock_mismatches(
        lock_pins((REPO_DIR / "requirements.lock").read_text(encoding="utf-8")),
        _installed_version,
    )
    if sys.version_info[:2] != (3, 12):
        problems.append(f"Python {platform.python_version()}; requirements.lock is for 3.12")
    cuda = torch.cuda.is_available()
    report = {
        "python": platform.python_version(),
        "torch": torch.__version__,
        "torch_cuda": torch.version.cuda,
        "cuda_available": cuda,
        "gpu": torch.cuda.get_device_name(0) if cuda else None,
        "lock_problems": problems,
    }
    print(json.dumps(report, indent=2))
    if args.require_gpu and not cuda:
        problems.append("No CUDA GPU visible to torch; pick a GPU runtime")
    if problems:
        print("Environment check FAILED:\n  " + "\n  ".join(problems))
        return 1
    print("Environment check passed: every requirements.lock pin is installed.")
    return 0


def _command_prerequisites(args: Any) -> int:
    prerequisites = admitted_run_prerequisites(REPO_DIR)
    missing = [p for p in prerequisites if not p.present]
    for prerequisite in prerequisites:
        mark = "ok     " if prerequisite.present else "MISSING"
        print(f"{mark} {prerequisite.pull_request}: {prerequisite.description}")
    if any(p.pull_request == PACKAGE_PIN_PREREQUISITE for p in missing):
        print(
            "This notebook holds no pin for the stock package the recipe's data config "
            "declares, so neither mode can stage it. Run a commit whose notebook pins that "
            "package; never add a pin that was not checked against the published manifest."
        )
        return 1
    if missing and args.mode == "full":
        print(
            "This commit lacks what the admitted run needs from "
            + ", ".join(sorted({p.pull_request for p in missing}))
            + ". Merge them and re-clone, or set RUN_MODE = 'smoke' for a mechanics check."
        )
        return 1
    if missing:
        print("Smoke mode: running without them. The result is not evidence.")
    return 0


def _stage_inputs(package_drive_dir: str, eodhd_drive_path: str) -> dict[str, Any]:
    selected = selected_package(REPO_DIR)
    package = stage_package(
        REPO_DIR,
        Path(package_drive_dir or selected.drive_dir),
        manifest=selected.manifest,
        manifest_sha256=selected.manifest_sha256,
        drive_inventory=selected.drive_inventory,
    )
    eodhd = stage_eodhd_market_file(REPO_DIR, eodhd_drive_path)
    return {
        "staged_at_utc": datetime.now(timezone.utc).isoformat(),
        "package": package.summary(),
        "eodhd_sp500_index": {
            "path": EODHD_MARKET_RELATIVE,
            "sha256": EODHD_MARKET_SHA256,
            "size_bytes": EODHD_MARKET_SIZE,
            "staging": eodhd,
        },
    }


def _command_stage(args: Any) -> int:
    summary = _stage_inputs(args.package_drive_dir, args.eodhd_drive_path)
    for item in [*summary["package"]["files"], summary["eodhd_sp500_index"]]:
        print(
            f"{item['staging']:>7}  {item['sha256'][:12]}  {item['size_bytes']:>10}  {item['path']}"
        )
    print(
        f"Package {summary['package']['package_id']} {summary['package']['package_revision']} "
        "and the EODHD file verified"
    )
    return 0


def _source_changes() -> str:
    """Changes git sees under the roots #144 records, untracked files included."""
    from mci_gru.evaluation.execution_provenance import SOURCE_ROOTS

    return _git("status", "--porcelain", "--", *SOURCE_ROOTS)


def _command_run(args: Any) -> int:
    import sys

    full = args.mode == "full"
    prerequisites = admitted_run_prerequisites(REPO_DIR)
    if full and any(not p.present for p in prerequisites):
        print("Refusing a full run: run the prerequisites check to see what is missing.")
        return 1
    if not os.environ.get("FRED_API_KEY", "").strip():
        print("Refusing to run: FRED_API_KEY is not set (Colab secret FRED_API_KEY).")
        return 1
    source_changes = _source_changes()
    if full and source_changes:
        print("Refusing a full run: the checkout's source has changes:\n" + source_changes)
        return 1
    recipe_text = (REPO_DIR / RECIPE_PATH).read_text(encoding="utf-8")
    slug = recipe_slug(recipe_text)
    commit = _git("rev-parse", "HEAD")
    run_tag = args.run_tag or (
        f"{datetime.now(timezone.utc):%Y%m%dT%H%M%SZ}-{args.mode}-{commit[:8]}"
    )
    local_dir = Path(args.local_root) / run_tag
    drive_dir = Path(args.drive_root) / run_tag
    if local_dir.exists() or drive_dir.exists():
        print(f"Refusing to reuse a run folder: {local_dir} or {drive_dir} already exists.")
        return 1
    # Staged again here, so a run never starts on inputs that were not verified.
    # Both steps reuse files already in place after re-hashing them.
    staging = _stage_inputs(args.package_drive_dir, args.eodhd_drive_path)
    overrides = build_run_overrides(
        recipe_overrides(recipe_text),
        run_dir=local_dir,
        experiment_name=slug,
        smoke=not full,
    )
    record = {
        "run_tag": run_tag,
        "mode": args.mode,
        "evidence": EVIDENCE_LABELS[args.mode],
        "recipe_slug": slug,
        "commit": commit,
        "source_changes": source_changes,
        "prerequisites": [
            {"pull_request": p.pull_request, "description": p.description, "present": p.present}
            for p in prerequisites
        ],
        "staging": staging,
        "overrides": overrides,
        "local_dir": str(local_dir),
        "drive_dir": str(drive_dir),
        "fred_api_key_set": True,
        "started_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    local_dir.mkdir(parents=True)
    write_json(local_dir / "colab_run_record.json", record)
    freeze = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"], capture_output=True, text=True, check=False
    )
    (local_dir / "pip_freeze.txt").write_text(freeze.stdout, encoding="utf-8")
    if args.tag_file:
        Path(args.tag_file).write_text(run_tag + "\n", encoding="utf-8")
    print(f"Run {run_tag}: {record['evidence']}")
    print(f"Local folder: {local_dir}\nDrive copy:   {drive_dir}")
    returncode = run_with_drive_sync(
        [sys.executable, "-u", "run_experiment.py", *overrides],
        cwd=REPO_DIR,
        local_dir=local_dir,
        drive_dir=drive_dir,
        every_seconds=args.sync_every,
    )
    record["finished_at_utc"] = datetime.now(timezone.utc).isoformat()
    record["returncode"] = returncode
    write_json(local_dir / "colab_run_record.json", record)
    try:
        sync_to_drive(local_dir, drive_dir)
    except OSError as error:
        print(f"The last copy to Drive failed ({error}); the run folder is still at {local_dir}")
    print(f"run_experiment.py exited {returncode}; outputs copied to {drive_dir}")
    return returncode


def main(argv: Sequence[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    commands = parser.add_subparsers(dest="command", required=True)
    check_env = commands.add_parser("check-env")
    check_env.add_argument("--require-gpu", action="store_true")
    prerequisites = commands.add_parser("prerequisites")
    prerequisites.add_argument("--mode", choices=sorted(EVIDENCE_LABELS), required=True)
    stage = commands.add_parser("stage")
    stage.add_argument("--package-drive-dir", default="")
    stage.add_argument("--eodhd-drive-path", default=EODHD_MARKET_DRIVE_PATH)
    run = commands.add_parser("run")
    run.add_argument("--mode", choices=sorted(EVIDENCE_LABELS), required=True)
    run.add_argument("--local-root", required=True)
    run.add_argument("--drive-root", required=True)
    run.add_argument("--run-tag", default="")
    run.add_argument("--sync-every", type=float, default=600.0)
    run.add_argument("--package-drive-dir", default="")
    run.add_argument("--eodhd-drive-path", default=EODHD_MARKET_DRIVE_PATH)
    run.add_argument("--tag-file", default="")
    args = parser.parse_args(argv)
    handler = {
        "check-env": _command_check_env,
        "prerequisites": _command_prerequisites,
        "stage": _command_stage,
        "run": _command_run,
    }[args.command]
    return handler(args)


if __name__ == "__main__":
    raise SystemExit(main())
