from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import date

    from cockpit.models import CockpitReport, GitHubAction, Workstream


REGISTER_COLUMNS = [
    "Workstream",
    "Status",
    "GitHub Issue / PR",
    "Branch / Worktree",
    "Source Of Truth",
    "Latest Artifact",
    "Last Verification",
    "Blocked On",
    "Next Action",
    "Owner",
    "Last Reviewed",
]


def render_workstream_register(workstreams: list[Workstream], generated_on: date) -> str:
    lines = [
        "# MCI-GRU Workstream Register",
        "",
        f"Generated by `scripts/refresh_cockpit.py` on {generated_on.isoformat()}.",
        "",
        "| " + " | ".join(REGISTER_COLUMNS) + " |",
        "| " + " | ".join("---" for _ in REGISTER_COLUMNS) + " |",
    ]
    for workstream in workstreams:
        lines.append("| " + " | ".join(_workstream_cells(workstream)) + " |")
    lines.append("")
    return "\n".join(lines)


def render_cockpit_packet(report: CockpitReport) -> str:
    lines = [
        f"# MCI-GRU Cockpit - {report.run_date.isoformat()}",
        "",
        f"**Run color:** {report.color.value}",
        "",
        "## Executive Summary",
        "",
        report.executive_summary,
        "",
    ]
    _extend_bullets(lines, "Git Tree Impact", report.git_tree_impact)
    _extend_decisions(lines, report)
    _extend_workstreams(lines, "Active Workstreams", report.active_workstreams)
    _extend_workstreams(lines, "Blocked Workstreams", report.blocked_workstreams)
    _extend_workstreams(lines, "Local-Only Work", report.local_only_work)
    _extend_workstreams(lines, "Stale Or Archive Candidates", report.stale_or_archive_candidates)
    _extend_actions(lines, "GitHub Actions Taken", report.github_actions_taken)
    _extend_actions(lines, "GitHub Actions Proposed Or Skipped", report.github_actions_skipped)
    _extend_bullets(lines, "Verification Notes", report.verification_notes)
    _extend_bullets(lines, "Evidence Gaps And Contradictions", report.evidence_gaps)
    return "\n".join(lines)


def _workstream_cells(workstream: Workstream) -> list[str]:
    return [
        _escape_cell(workstream.name),
        _escape_cell(workstream.status.value),
        _escape_cell(workstream.tracker),
        _escape_cell(workstream.continuation),
        _escape_cell(workstream.source_of_truth),
        _escape_cell(workstream.latest_artifact),
        _escape_cell(workstream.last_verification),
        _escape_cell(workstream.blocked_on),
        _escape_cell(workstream.next_action),
        _escape_cell(workstream.owner),
        workstream.last_reviewed.isoformat(),
    ]


def _extend_decisions(lines: list[str], report: CockpitReport) -> None:
    lines.extend(["## Decision Queue", ""])
    if not report.decisions:
        lines.extend(["No user decisions queued.", ""])
        return
    for decision in report.decisions:
        lines.extend(
            [
                f"- **{decision.workstream}:** {decision.question}",
                f"  Options: {decision.options}",
            ]
        )
    lines.append("")


def _extend_workstreams(lines: list[str], title: str, workstreams: list[Workstream]) -> None:
    lines.extend([f"## {title}", ""])
    if not workstreams:
        lines.extend(["None.", ""])
        return
    for workstream in workstreams:
        lines.append(
            f"- **{workstream.name}** ({workstream.status.value}): {workstream.next_action}"
        )
    lines.append("")


def _extend_actions(lines: list[str], title: str, actions: list[GitHubAction]) -> None:
    lines.extend([f"## {title}", ""])
    if not actions:
        lines.extend(["None.", ""])
        return
    for action in actions:
        lines.append(f"- `{action.action}` on {action.target}: {action.reason}")
    lines.append("")


def _extend_bullets(lines: list[str], title: str, values: list[str]) -> None:
    lines.extend([f"## {title}", ""])
    if not values:
        lines.extend(["None.", ""])
        return
    for value in values:
        lines.append(f"- {value}")
    lines.append("")


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", "<br>")
