from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import date

    from cockpit.models import (
        AutoDecisionChange,
        AutoDisposition,
        AutoOverride,
        AutoWorkstreamDecision,
        CockpitReport,
        GitHubAction,
        LowConfidenceDecision,
        Workstream,
    )


REGISTER_COLUMNS = [
    "Workstream",
    "Status",
    "GitHub Issue / PR",
    "Branch / Worktree",
    "Source Of Truth",
    "Latest Artifact",
    "Last Verification",
    "Blocked On",
    "Next Action",
    "Owner",
    "Last Reviewed",
]


def render_workstream_register(workstreams: list[Workstream], generated_on: date) -> str:
    lines = [
        "# MCI-GRU Workstream Register",
        "",
        f"Generated by `scripts/refresh_cockpit.py` on {generated_on.isoformat()}.",
        "",
        "| " + " | ".join(REGISTER_COLUMNS) + " |",
        "| " + " | ".join("---" for _ in REGISTER_COLUMNS) + " |",
    ]
    for workstream in workstreams:
        lines.append("| " + " | ".join(_workstream_cells(workstream)) + " |")
    lines.append("")
    return "\n".join(lines)


def render_cockpit_packet(report: CockpitReport) -> str:
    lines = [
        f"# MCI-GRU Cockpit - {report.run_date.isoformat()}",
        "",
        f"**Run color:** {report.color.value}",
        "",
        "## Executive Summary",
        "",
        report.executive_summary,
        "",
    ]
    _extend_bullets(lines, "Git Tree Impact", report.git_tree_impact)
    _extend_decisions(lines, report)
    _extend_workstreams(lines, "Workstreams Needing Decisions", report.decision_workstreams)
    _extend_workstreams(lines, "Canonical / Ready Queue", report.active_workstreams)
    _extend_workstreams(lines, "Blocked Workstreams", report.blocked_workstreams)
    _extend_workstreams(lines, "Local-Only Work", report.local_only_work)
    _extend_workstreams(lines, "Parked Queue", report.parked_workstreams)
    _extend_workstreams(
        lines,
        "Archive / Cleanup Candidates",
        report.stale_or_archive_candidates,
    )
    _extend_actions(lines, "GitHub Actions Taken", report.github_actions_taken)
    _extend_actions(lines, "GitHub Actions Proposed Or Skipped", report.github_actions_skipped)
    _extend_bullets(lines, "Verification Notes", report.verification_notes)
    _extend_bullets(lines, "Evidence Gaps And Contradictions", report.evidence_gaps)
    if report.auto_decisions_enabled:
        _extend_auto_dispositions(lines, report.auto_dispositions)
        _extend_auto_statuses(lines, report.auto_workstream_decisions)
        if report.decision_changes:
            _extend_decision_changes(lines, report.decision_changes)
        _extend_low_confidence(lines, report.low_confidence_decisions)
        _extend_overrides(lines, report.overrides_applied)
    return "\n".join(lines)


def _workstream_cells(workstream: Workstream) -> list[str]:
    return [
        _escape_cell(workstream.name),
        _escape_cell(workstream.status.value),
        _escape_cell(workstream.tracker),
        _escape_cell(workstream.continuation),
        _escape_cell(workstream.source_of_truth),
        _escape_cell(workstream.latest_artifact),
        _escape_cell(workstream.last_verification),
        _escape_cell(workstream.blocked_on),
        _escape_cell(workstream.next_action),
        _escape_cell(workstream.owner),
        workstream.last_reviewed.isoformat(),
    ]


def _extend_decisions(lines: list[str], report: CockpitReport) -> None:
    lines.extend(["## Decision Queue", ""])
    if not report.decisions:
        lines.extend(["No user decisions queued.", ""])
        return
    for decision in report.decisions:
        lines.extend(
            [
                f"- **{decision.workstream}:** {decision.question}",
                f"  Options: {decision.options}",
            ]
        )
    lines.append("")


def _extend_workstreams(lines: list[str], title: str, workstreams: list[Workstream]) -> None:
    lines.extend([f"## {title}", ""])
    if not workstreams:
        lines.extend(["None.", ""])
        return
    for workstream in workstreams:
        lines.append(
            f"- **{workstream.name}** ({workstream.status.value}): {workstream.next_action}"
        )
    lines.append("")


def _extend_actions(lines: list[str], title: str, actions: list[GitHubAction]) -> None:
    lines.extend([f"## {title}", ""])
    if not actions:
        lines.extend(["None.", ""])
        return
    for action in actions:
        lines.append(f"- `{action.action}` on {action.target}: {action.reason}")
    lines.append("")


def _extend_bullets(lines: list[str], title: str, values: list[str]) -> None:
    lines.extend([f"## {title}", ""])
    if not values:
        lines.extend(["None.", ""])
        return
    for value in values:
        lines.append(f"- {value}")
    lines.append("")


def _extend_auto_dispositions(
    lines: list[str],
    decisions: dict[str, AutoDisposition],
) -> None:
    lines.extend(["## Auto-Dispositions Applied", ""])
    if not decisions:
        lines.extend(["None.", ""])
        return
    for branch, decision in sorted(decisions.items()):
        lines.append(
            f"- **{branch}** → {decision.disposition.value}; rule `{decision.rule}`; "
            f"confidence {decision.confidence.value}; evidence: {decision.evidence}"
        )
        lines.append(f"  Alternatives: {_alternatives(decision.alternatives)}")
    lines.append("")


def _extend_auto_statuses(
    lines: list[str],
    decisions: dict[str, AutoWorkstreamDecision],
) -> None:
    lines.extend(["## Auto-Statuses Applied", ""])
    if not decisions:
        lines.extend(["None.", ""])
        return
    for name, decision in sorted(decisions.items()):
        canonical = decision.canonical_surface or "none"
        lines.append(
            f"- **{name}** → {decision.status.value}; canonical `{canonical}`; "
            f"rule `{decision.rule}`; confidence {decision.confidence.value}; "
            f"evidence: {decision.evidence}"
        )
        lines.append(f"  Alternatives: {_alternatives(decision.alternatives)}")
    lines.append("")


def _extend_low_confidence(
    lines: list[str],
    decisions: list[LowConfidenceDecision],
) -> None:
    lines.extend(["## Low-Confidence Decisions", ""])
    if not decisions:
        lines.extend(["None.", ""])
        return
    for decision in sorted(decisions, key=lambda item: (item.kind, item.target)):
        lines.append(
            f"- **{decision.kind} {decision.target}** → {decision.choice}; "
            f"rule `{decision.rule}`; confidence low; evidence: {decision.evidence}"
        )
        lines.append(f"  Alternatives: {_alternatives(decision.alternatives)}")
    lines.append("")


def _extend_decision_changes(lines: list[str], changes: list[AutoDecisionChange]) -> None:
    lines.extend(["## Generated Decision Changes", ""])
    if not changes:
        lines.extend(["None.", ""])
        return
    for item in changes:
        label = f"**{item.kind} {item.target}**"
        if item.change == "added":
            description = f"added as {item.after}"
        elif item.change == "removed":
            description = f"removed (was {item.before})"
        elif item.change == "choice":
            description = f"choice changed {item.before} → {item.after}"
        elif item.change == "confidence":
            description = f"confidence changed {item.before} → {item.after}"
        elif item.change == "metadata":
            description = f"metadata `{item.field}` changed {item.before} → {item.after}"
        elif item.change == "override-added":
            description = f"override added; generated {item.before} → explicit {item.after}"
        elif item.change == "override-changed":
            description = (
                f"override changed; explicit {item.before} metadata updated"
                if item.before == item.after
                else f"override changed; explicit {item.before} → explicit {item.after}"
            )
        else:
            description = (
                f"override cleared; explicit {item.before} → no generated decision"
                if item.after == "none"
                else f"override cleared; explicit {item.before} → generated {item.after}"
            )
        lines.append(f"- {label}: {description}")
    lines.append("")


def _extend_overrides(lines: list[str], overrides: list[AutoOverride]) -> None:
    lines.extend(["## Overrides Applied", ""])
    if not overrides:
        lines.extend(["None.", ""])
        return
    for override in sorted(overrides, key=lambda item: (item.kind, item.target)):
        lines.append(
            f"- **{override.kind} {override.target}**: generated {override.generated_choice}, "
            f"override {override.override_choice}; rule `{override.rule}`; "
            f"confidence {override.confidence.value}; evidence: {override.evidence}"
        )
        lines.append(f"  Alternatives: {_alternatives(override.alternatives)}")
    lines.append("")


def _alternatives(values: tuple[str, ...]) -> str:
    return "; ".join(values) if values else "none"


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", "<br>")
